demo:
  title: RBAC demo
  banner:
    title: Warning
    content: The blog will be down tomorrow.
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://database:5432/mydatabase
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: secret
  liquibase:
    #  enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true